# Generated by Django 3.0.6 on 2020-05-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'managed': False, 'ordering': ['nombre'], 'verbose_name_plural': 'Colores'},
        ),
        migrations.AlterModelOptions(
            name='localidades',
            options={'managed': False, 'verbose_name_plural': 'Localidades'},
        ),
        migrations.AlterModelOptions(
            name='marcas',
            options={'managed': False, 'ordering': ['nombre'], 'verbose_name_plural': 'Marcas'},
        ),
        migrations.AlterModelOptions(
            name='talles',
            options={'managed': False, 'ordering': ['nombre'], 'verbose_name_plural': 'Talles'},
        ),
        migrations.AlterField(
            model_name='imagenarticulo',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='articulos/'),
        ),
    ]
