# Generated by Django 3.0.6 on 2020-05-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20200514_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenarticulo',
            name='principal',
            field=models.BooleanField(default=True),
        ),
    ]
