# Generated by Django 3.0.6 on 2020-05-14 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_imagenarticulo_principal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenarticulo',
            name='principal',
            field=models.BooleanField(default=False),
        ),
    ]
