# Generated by Django 3.0.6 on 2020-05-17 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_auto_20200517_1036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historial',
            old_name='producto',
            new_name='articulo',
        ),
        migrations.AlterField(
            model_name='historial',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 17, 11, 6, 6, 247998)),
        ),
    ]
