# Generated by Django 3.0.6 on 2020-05-27 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0014_auto_20200525_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 27, 16, 13, 43, 683511)),
        ),
        migrations.DeleteModel(
            name='Favoritos',
        ),
    ]
