# Generated by Django 3.0.6 on 2020-05-27 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0017_auto_20200527_1629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulos',
            options={'managed': True, 'verbose_name': 'Articulo', 'verbose_name_plural': 'Articulos'},
        ),
        migrations.AlterField(
            model_name='historial',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 27, 16, 29, 55, 252730)),
        ),
    ]
