# Generated by Django 3.0.6 on 2020-05-31 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cel_no',
            field=models.CharField(default='', max_length=100, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(default='', max_length=250, verbose_name='Domicilio'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(default='', max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(default='', max_length=50, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.CharField(default='', max_length=20, verbose_name='Cod Post'),
        ),
    ]
