# Generated by Django 3.0.6 on 2020-05-23 18:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 23, 18, 35, 48, 995639), verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='state',
            field=models.CharField(choices=[('P', 'Publicado'), ('B', 'Borrador'), ('A', 'Anulado')], max_length=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(default='', max_length=150, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 23, 18, 35, 48, 995639), verbose_name='Actualizado'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AlterField(
            model_name='blogdetail',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Contenido'),
        ),
    ]
