# Generated by Django 3.0.6 on 2020-05-31 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200531_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 31, 10, 15, 55, 547581), verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 31, 10, 15, 55, 547581), verbose_name='Actualizado'),
        ),
    ]
