# Generated by Django 3.0.6 on 2020-05-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paramsist',
            fields=[
                ('idparamsist', models.AutoField(db_column='idParamSist', primary_key=True, serialize=False)),
                ('parametro', models.CharField(db_column='Parametro', max_length=100)),
                ('valor', models.CharField(db_column='Valor', max_length=100)),
                ('detalle', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Parametros de sistema',
                'verbose_name_plural': 'Parametros de sistema',
                'db_table': 'paramsist',
                'managed': False,
            },
        ),
    ]
