# Generated by Django 3.0.6 on 2020-05-14 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100)),
                ('tipo_seccion', models.CharField(choices=[('B2', 'Banner principal'), ('S1', 'Seccion Uno')], default='', max_length=2)),
                ('descripcion', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Seccion',
                'verbose_name_plural': 'Secciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DetalleSecciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', max_length=100)),
                ('detalle', models.TextField(blank=True, default='')),
                ('articulo', models.PositiveIntegerField(blank=True, default=0)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inicio.Secciones')),
            ],
        ),
    ]
