# Generated by Django 3.0.6 on 2020-05-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_detallesecciones_secciones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallesecciones',
            options={'verbose_name': 'Detalle Secciones', 'verbose_name_plural': 'Detalle Secciones'},
        ),
        migrations.AddField(
            model_name='detallesecciones',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='portadas/'),
        ),
        migrations.AddField(
            model_name='secciones',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
