# Generated by Django 3.0.6 on 2020-05-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_auto_20200514_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='secciones',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
