# Generated by Django 3.0.6 on 2020-05-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_auto_20200514_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='secciones',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='portadas/'),
        ),
    ]
