# Generated by Django 3.0.6 on 2020-05-17 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0012_auto_20200517_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secciones',
            name='finaliza',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 17, 12, 53, 9, 875160)),
        ),
    ]
