# Generated by Django 3.0.6 on 2020-05-31 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0020_auto_20200527_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secciones',
            name='finaliza',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 31, 9, 41, 27, 858743)),
        ),
    ]
