# Generated by Django 3.0.6 on 2020-08-19 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0024_auto_20200604_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secciones',
            name='finaliza',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 19, 15, 48, 20, 938671)),
        ),
    ]
